require 'strscan'
require 'csv'
#require 'diff_match_patch'
require 'diff_match_patch_native'

module Suspension; end

require 'suspension/absolute_suspended_tokens'
require 'suspension/diff_algorithm'
require 'suspension/diff_extractor'
require 'suspension/errors'
require 'suspension/relative_suspended_tokens'
require 'suspension/repositext_tokens'
require 'suspension/string_comparer'
require 'suspension/suspended_token'
require 'suspension/suspender'
require 'suspension/text_replayer'
require 'suspension/token'
require 'suspension/token_remover'
require 'suspension/token_replacer'
require 'suspension/unsuspender'
